#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 "oracle_url" <<-EOF
  DROP TABLE BOOKS;
  DROP TABLE VIDEOS;
  DROP TABLE RENTALORDER;
  DROP TABLE ORDERS;
  DROP TABLE SUPPLIERITEMS;
  DROP TABLE SUPPLIERS;
  DROP TABLE CUSTOMER;
  DROP TABLE EMPLOYEE;
  DROP TABLE PAYMENTMETHOD;
  DROP TABLE LIBRARYITEM;
  DROP TABLE PERSON;
  DROP TABLE MEMBERSHIP;
  exit;
EOF
